### ISSUE TITLE
Missing SHACL validation result in validate API output

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/register#100]
Validating https://data.spinque.com/ld/data/oorlogsbronnen/oorlog_in_blik/ results in:
```
Status: 400

{"quads":{}}
```

**Comment by ddeboer** [comment]
Duplicate of #90.

**Comment by coret** [comment]
https://github.com/netwerk-digitaal-erfgoed/register/pull/79 was not propagated to demo
now fixed via https://github.com/netwerk-digitaal-erfgoed/registry-demo/commit/1323dac91d2625128f1098beecebf410760a48d8
