### ISSUE TITLE
Check SHACL

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/register#18]
In #8 we added dataset description validation based on SHACL. The SHACL file is all right, but not yet complete:  https://github.com/netwerk-digitaal-erfgoed/registry-api/blob/main/shacl/dataset.jsonld

@coret Please have a look at that SHACL file and feel free to submit a PR to improve it.

**Comment by ddeboer** [comment]
Additional question: can we support both DCAT and Schema with the same SHACL definition (using ORs, if any such thing exists in SHACL) or do we need to separate files?

**Comment by coret** [comment]
- SHACL validating a empty file results in a error stating the input is invalid JSON
- SHACL validating valid JSON file which doesn't contain a dataset returns `[ a sh:ValidationReport ; sh:conforms  true ] .` - this is a case we have to provide extra checks for (before SHACL validation?)
- Current schema.org/Dataset SHACL is missing DataCatalog req's, can be added, will still work on only Dataset (will add)
- DCAT and schema.or/Dataset SHACL's can be combined into one! (will do)

**Comment by ddeboer** [comment]
See #58 for a set of automated SHACL tests.

**Comment by ddeboer** [comment]
Thanks @coret! I’ve validated
