### ISSUE TITLE
Use DCAT as internal data format

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/register#35]
Reason:

- backed by W3C
- extensions such as geo etc.

**Comment by ddeboer** [comment]
@coret Can you please link your Schema/DCAT mapping here?

**Comment by coret** [comment]
schema:Dataset | dcat:Dataset |  
-- | -- | --
schema:identifier | dct:identifier | Required
schema:name | dct:title | Required
schema:description | dct:description | Required
schema:creator | dct:creator | Required
schema:license | dct:license | Required
schema:datePublished | dct:issued | Required
schema:dateModified | dct:modified | Required
schema:distribution | dct:distribution | Required
schema:publisher | dct:publisher | Recommended
schema:inLanguage | dct:language | Recommended
schema:isBasedOnUrl | dct:source | Recommended
schema:citation | - | Recommended
schema:genre | - | Recommended
schema:keywords | dct:keyword | Recommended
schema:includedInDataCatalog | - | Recommended
schema:dateCreated | dct:created | Recommended
schema:spatialCoverage | dct:spatial | Recommended
schema:temporalCoverage | dct:temporal | Recommended
schema:version | owl:versionInfo | Recommended
schema:mainEntityOfPage | dct:landingPage | Recommended

schema:DataDownload | dcat:Distribution |  
-- | -- | --
schema:fileFormat | dcat:mediaType | Required
schema:encodingFormat | dct:format | Required
schema:contentURL | dcat:accessURL | Required
schema:datePublished | dct:issued | Required
schema:dateModified | dct:modified | Required
schema:description | dct:description | Recommended
schema:inLanguage | - | Recommended
schema:license | dct:license | Recommended
schema:name | dct:title | Recommended
schema:contentSize | dcat:byteSize | Recommended

schema:Organisation (or Person) | foaf:Organization (or Person) |  
-- | -- | --
schema:name | foaf:name | Required
schema:email | foaf:mbox | Recommended
schema:url | foaf:workplaceHomepage | Required
schema:sameAs | owl:sameAs | Recommended

Question 1: what to do when there is no DCAT property? Keep schema property?
Question 2: is this conversion table enough for implementation or do we also need to look into ranges?

**Comment by ddeboer** [comment]
`schema:alternateName` was missing, so I added `dct:alternative`.

Changed `dct:landingPage` to `dcat:landingPage`.
