### ISSUE TITLE
Testcases

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/register#39]
Add (preferable automated)  tests for API

**Comment by coret** [comment]
Start with validation tescases, datasets (JSON-LD) in testsuite/datasets folder

**Comment by ivozandhuis** [comment]
Should https://littest.hosting.deventit.net/Atlantispubliek/data/set/catalog.jsonld validate without errors? The Google dataset parser warns there is no licence added.

**Comment by coret** [comment]
Nope, added https://github.com/netwerk-digitaal-erfgoed/register/issues/50

**Comment by ddeboer** [comment]
Fixed #50.

**Comment by ddeboer** [comment]
In #58, #60 and #62 I’ve added automated tests for the SHACL validation, the crawler and the HTTP server.
