### ISSUE TITLE
502 Bad Gateway using DeventIT catalog.ttl

### ISSUE THREAD

**Issue by ivozandhuis** [netwerk-digitaal-erfgoed/register#48]
Using: https://demo.netwerkdigitaalerfgoed.nl/register/validate.php

Validating: https://littest.hosting.deventit.net/Atlantispubliek/data/set/catalog.jsonld or https://littest.hosting.deventit.net/Atlantispubliek/data/set/catalog.rdf results in status: 200.

Validating: https://littest.hosting.deventit.net/Atlantispubliek/data/set/catalog.ttl results in status: 502 Bad Gateway + error message.

Possible solution: I noticed the ttl-file has a BOM. My CLI RDF parser (raptor) cannot handle that. Maybe your parser neither?

**Comment by ddeboer** [comment]
Comunica throws an error when querying https://littest.hosting.deventit.net/Atlantispubliek/data/set/catalog.ttl; reported at https://github.com/comunica/comunica/issues/778.

**Comment by coret** [comment]
Have tested the suggestion of the UTF8 BOM being the problem: made a copy of the file **without** a BOM (http://lab.coret.org/rdf/littest.deventit.ttl) and this file doesn't throw an error.

**Comment by ddeboer** [comment]
> Use of a BOM is neither required nor recommended for UTF-8, but may be encountered in contexts where UTF-8 data is converted from other encoding forms that use a BOM or where the BOM is used as a UTF-8 signature. 

https://www.unicode.org/versions/Unicode5.0.0/ch02.pdf (p. 36)

@ivozandhuis UTF-8 BOMs being ‘not recommended’, can you ask DeventIT to produce RDF without the BOM?

**Comment by ivozandhuis** [comment]
done!

**Comment by ddeboer** [comment]
On our side, we’ll catch the error and return a 406 status code.

**Comment by ivozandhuis** [comment]
nice!

**Comment by ivozandhuis** [comment]
For what it's worth: DEVENTit ticket 182 resolved :-)
