### ISSUE TITLE
DCAT shacl used on schema datasetdescription

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/register#55]
When validating the datacatalog https://www.openarch.nl/datasets/ (which uses schema.org/Dataset) using the API I get the following result (in which I recognize the DCAT shacl):
```
Status: 400

_:b2 a <http://www.w3.org/ns/shacl#ValidationResult>;
    <http://www.w3.org/ns/shacl#resultSeverity> <http://www.w3.org/ns/shacl#Violation>;
    <http://www.w3.org/ns/shacl#sourceConstraintComponent> <http://www.w3.org/ns/shacl#MinCountConstraintComponent>;
    <http://www.w3.org/ns/shacl#sourceShape> _:df_28_3.
_:df_28_3 <http://www.w3.org/ns/shacl#path> <http://purl.org/dc/terms/license>;
    <http://www.w3.org/ns/shacl#minCount> 1.
_:b2 <http://www.w3.org/ns/shacl#focusNode> <https://www.openarch.nl/id/dataset_ade>;
    <http://www.w3.org/ns/shacl#resultPath> <http://purl.org/dc/terms/license>;
    <http://www.w3.org/ns/shacl#resultMessage> "Less than 1 values".
_:report a <http://www.w3.org/ns/shacl#ValidationReport>;
    <http://www.w3.org/ns/shacl#conforms> false;
    <http://www.w3.org/ns/shacl#result> _:b2.
```

Similar result when validating a single dataset (https://www.openarch.nl/datasets/ade).

**Comment by ddeboer** [comment]
Of course, because we’re now using DCAT internally. Please note that the DCAT SHACL is applied to the description which has already been transformed from Schema to DCAT.

This error specifically is about https://www.openarch.nl/datasets having `schema:license` as blank nodes without the IRI of the real thing (note that `url` is not the same as `@id`):

```json
"license": {
  "@type": "CreativeWork",
  "name": "Creative Commons 0",
  "url": "http:\/\/creativecommons.org\/publicdomain\/zero\/1.0\/"
}
```

As I wrote in #53:

> Prevent license blank nodes by allowing IRIs only.

**Comment by coret** [comment]
We must discuss this, because this makes the validation results for even more confusing. We should validate the datasetdecription as published, if present and valid (schema or DCAT) then convert to DCAT (wonder if validating the converted datasetdescription is necessary, if we do, any errors are on us, not the publisher).

**Comment by ddeboer** [comment]
Since #58 we validate the original dataset description, whether that is in DCAT or Schema.org.
