### ISSUE TITLE
Configure allowed domains

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/register#64]
* Add allowed domains graph: only requests from allowed domains can be added (return a 403 Forbidden otherwise); validation is allowed for all domains.
* If only a main domain name is configured, accept requests from all subdomains of that domain.
* Add documentation on how users can have their URL added to the allow list.

@coret Can you supply an initial set of domain names?

**Comment by coret** [comment]
Something like [allowed_domain_names](https://triplestore.netwerkdigitaalerfgoed.nl/resource?uri=https:%2F%2Fdata.netwerkdigitaalerfgoed.nl%2Fregistry%2Fallowed_domain_names&role=context) ?

**Comment by ddeboer** [comment]
Done in #70.

@coret Can you add a section to [the FAQ](https://demo.netwerkdigitaalerfgoed.nl/register/faq.php) about the allow list?
