### ISSUE TITLE
Adding form-generated dataset results in http 500

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/register#72]
Adding https://demo.netwerkdigitaalerfgoed.nl/register/dataset.php?guid=78154EBC-8B0A-4E9C-A2A0-5740B80E88DA (dataset generated via demonstrator form, validated via API) results in a http 500 error.

`{"level":50,"time":1614075896903,"pid":19,"hostname":"registry-api-xxx-xxx","reqId":6,"req":{"method":"POST","url":"/datasets","hostname":"demo.netwerkdigitaalerfgoed.nl","remoteAddress":"xxx.xxx.xxx.xxx","remotePort":xxx},"res":{"statusCode":500},"err":{"type":"NoDatasetFoundAtUrl","message":"","stack":"Error\n    at Object.fetch (/app/build/src/fetch.js:38:15)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Object.<anonymous> (/app/build/src/server.js:91:30)"},"msg":""}`

So, our code can find a Dataset but Communica can not find a dataset (inlined schema.org/dataset) in https://demo.netwerkdigitaalerfgoed.nl/register/dataset.php?guid=78154EBC-8B0A-4E9C-A2A0-5740B80E88DA ? 
@ddeboer could you investigate with `comunica-sparql`

**Comment by ddeboer** [comment]
For one or another reason, Comunica doesn’t play well with your

```
"@context": {
  "@vocab": "http://schema.org/"
},
```

but is perfectly happy with:

```
"@context": "http://schema.org/",
```

While the latter is simply (and which I therefore recommend), we shouldn’t fail on the former syntax (both are valid JSON-LD).
