### ISSUE TITLE
Validate dataset description

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/register#8]
This functionality can be provided stand-alone to clients for checking conformance of their dataset description to NDE standards (https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#dataset-information). The functionality may also be reused in #2.  

### Questions

- Will SHACL suffice or do we need additional validation methods?
- Which standard can we use for providing validation feedback to clients?

**Comment by coret** [comment]
The current validation report is shown in N-triples. 
Is it possible to use a more human-friendly representation like triples or JSON-LD?
```
_:b5 a <http://www.w3.org/ns/shacl#ValidationResult>;
    <http://www.w3.org/ns/shacl#resultSeverity> <http://www.w3.org/ns/shacl#Violation>;
    <http://www.w3.org/ns/shacl#sourceConstraintComponent> <http://www.w3.org/ns/shacl#MinCountConstraintComponent>;
    <http://www.w3.org/ns/shacl#sourceShape> _:df_7_4.
_:df_7_4 <http://www.w3.org/ns/shacl#path> <http://schema.org/creator>;
    <http://www.w3.org/ns/shacl#minCount> 1;
    <http://www.w3.org/ns/shacl#class> <http://schema.org/Organization>;
    <http://www.w3.org/ns/shacl#node> "schema:CreatorShape".
_:b5 <http://www.w3.org/ns/shacl#focusNode> <http://data.bibliotheken.nl/id/dataset/nbt>;
    <http://www.w3.org/ns/shacl#resultPath> <http://schema.org/creator>;
    <http://www.w3.org/ns/shacl#resultMessage> "Less than 1 values".
_:b6 a <http://www.w3.org/ns/shacl#ValidationResult>;
    <http://www.w3.org/ns/shacl#resultSeverity> <http://www.w3.org/ns/shacl#Violation>;
    <http://www.w3.org/ns/shacl#sourceConstraintComponent> <http://www.w3.org/ns/shacl#MinCountConstraintComponent>;
    <http://www.w3.org/ns/shacl#sourceShape> _:df_7_2.
_:df_7_2 <http://www.w3.org/ns/shacl#path> <http://schema.org/description>;
    <http://www.w3.org/ns/shacl#minCount> 1.
_:b6 <http://www.w3.org/ns/shacl#focusNode> _:n3-3;
    <http://www.w3.org/ns/shacl#resultPath> <http://schema.org/description>;
    <http://www.w3.org/ns/shacl#resultMessage> "Less than 1 values".
_:b7 a <http://www.w3.org/ns/shacl#ValidationResult>;
    <http://www.w3.org/ns/shacl#resultSeverity> <http://www.w3.org/ns/shacl#Violation>;
    <http://www.w3.org/ns/shacl#sourceConstraintComponent> <http://www.w3.org/ns/shacl#MinCountConstraintComponent>;
    <http://www.w3.org/ns/shacl#sourceShape> _:df_7_4;
    <http://www.w3.org/ns/shacl#focusNode> _:n3-3;
    <http://www.w3.org/ns/shacl#resultPath> <http://schema.org/creator>;
    <http://www.w3.org/ns/shacl#resultMessage> "Less than 1 values".
_:b8 a <http://www.w3.org/ns/shacl#ValidationResult>;
    <http://www.w3.org/ns/shacl#resultSeverity> <http://www.w3.org/ns/shacl#Violation>;
    <http://www.w3.org/ns/shacl#sourceConstraintComponent> <http://www.w3.org/ns/shacl#MinCountConstraintComponent>;
    <http://www.w3.org/ns/shacl#sourceShape> _:df_7_5.
_:df_7_5 <http://www.w3.org/ns/shacl#path> <http://schema.org/distribution>;
    <http://www.w3.org/ns/shacl#minCount> 1;
    <http://www.w3.org/ns/shacl#class> <http://schema.org/DataDownload>;
    <http://www.w3.org/ns/shacl#node> "schema:DistributionShape".
_:b8 <http://www.w3.org/ns/shacl#focusNode> _:n3-3;
    <http://www.w3.org/ns/shacl#resultPath> <http://schema.org/distribution>;
    <http://www.w3.org/ns/shacl#resultMessage> "Less than 1 values".
_:report a <http://www.w3.org/ns/shacl#ValidationReport>;
    <http://www.w3.org/ns/shacl#conforms> false;
    <http://www.w3.org/ns/shacl#result> _:b5, _:b6, _:b7, _:b8.
```

**Comment by EnnoMeijers** [comment]
Tip: for the LODA validation reports I loaded the raw report into the triplestore and used a sparql query to generate a human readable report. Maybe this makes sense when you also use the stored reports for logging and debugging?

**Comment by coret** [comment]
@EnnoMeijers which sparql query did you use?

Understanding the validation report still requires a lot of effort. For example, the validation reports I posted is for [https://data.bibliotheken.nl/doc/dataset/nbt.ttl](https://data.bibliotheken.nl/doc/dataset/nbt.ttl). I still do not understand the message about the creator (yes it's missing, but why report it twice in b5 and b7) and the missing distribution (source has distribution with the 2 properties required in the shape)... I think the minimal [shape file](https://github.com/netwerk-digitaal-erfgoed/registry-api/blob/main/shacl/dataset.jsonld) we use is correct.

**Comment by EnnoMeijers** [comment]
See my extremely simple query at: https://github.com/netwerk-digitaal-erfgoed/lod-aggregator/blob/master/queries/list-errors.rq

I bet this behavior is caused by the use of the CreatorShape. I ended up flattening the shape definitions in order to get straightforward error messages. By the way: I really prefer turtle for shape definitions, can we have a vote on this ;)

**Comment by coret** [comment]
I do like the presentation of validation results via [SHACL Play!](https://shacl-play.sparna.fr/play/validate?url=https://data.bibliotheken.nl/doc/dataset/nbt.ttl&shapesUrl=https://demo.netwerkdigitaalerfgoed.nl/datasets/forms/shacl/publicatiemodel.ttl).  Strange thing is that this tool gives an error on our [shape file](https://github.com/netwerk-digitaal-erfgoed/registry-api/blob/main/shacl/dataset.jsonld), I had to use an [older version](https://demo.netwerkdigitaalerfgoed.nl/datasets/forms/shacl/publicatiemodel.ttl) or our SHACL. Also, this reports also mentions a missing schema:distribution property (and this report format doesn't help me in understanding this violation).

**Comment by coret** [comment]
Found the issue, it's in the data (cc @renevoorburg), specifically:
```
schema:mainEntityOfPage       [ a                    schema:WebPage , schema:Dataset ;
```
Because the mainEntityOfPage is defined as a Dataset too, the Dataset rules apply on the mainEntityOfPage , and this mainEntityOfPage doesn't have a creator nor distributions! I found this by deleting parts of the SHACL and data until there where 0 errors. I think I would have found the issue sooner if the focusNode properties were included, but these seem to be absent in shacl validation reports (in general)?

**Comment by ddeboer** [comment]
@coret I consider this issue closed, as the datasets are being validated. Please see #18 for improving the _contents_ of our SHACL file and create a separate issue for the presentation of validation errors.

**Comment by coret** [comment]
@ddeboer kun jij nog eens kijken hoe we onderstaande in SHACL kunnen opvangen (zodat de validatie goed gaat):

```
1. <id/dataset/nbt>  a                   schema:Dataset ;
2.        schema:identifier             <id/dataset/nbt> ;
3.        schema:mainEntityOfPage       <doc/dataset/nbt> ;
4.        schema:mainEntityOfPage       [ a                    schema:WebPage , schema:Dataset ;
                                          schema:dateModified  "2021-11-15"^^xsd:date ;
                                          schema:license       <http://creativecommons.org/publicdomain/zero/1.0/> ;
                                          schema:mainEntity    <id/dataset/nbt> ;
                                          schema:name          "Metadata beschrijving dataset NBT"@nl ;
                                          owl:sameAs           <doc/dataset/nbt>
                                      ] ;
```

Onze SHACL klaagt nu over de schema:mainEntityOfPage property dat er properties missen die verplicht zijn voor een schema:Dataset

Uit dataset: https://data.bibliotheken.nl/doc/dataset/nbt.ttl

**Comment by ddeboer** [comment]
Moved to a new issue.
